/**
 * worker.js - Web Worker for LLM inference
 * 
 * Runs WASM inference in a separate thread to keep UI responsive.
 */

// Import WASM module (generated by Emscripten)
importScripts('llama-tiny.js');

let Module = null;
let model = null;
let ctx = null;
let aborted = false;

// Initialize WASM module
async function init() {
    Module = await createLlamaTinyModule({
        print: (text) => self.postMessage({ type: 'log', data: text }),
        printErr: (text) => self.postMessage({ type: 'error', data: text })
    });
    
    // Initialize library
    const result = Module._llama_init();
    if (result !== 0) {
        throw new Error('Failed to initialize llama library');
    }
    
    return true;
}

// Load model from ArrayBuffer
async function loadModel(buffer, contextSize = 0) {
    // Free existing model
    if (ctx) {
        Module._llama_free_context(ctx);
        ctx = null;
    }
    if (model) {
        Module._llama_free_model(model);
        model = null;
    }
    
    // Allocate WASM memory for model
    const ptr = Module._malloc(buffer.byteLength);
    Module.HEAPU8.set(new Uint8Array(buffer), ptr);
    
    // Load model
    model = Module._llama_load_model(ptr, buffer.byteLength, contextSize);
    
    if (!model) {
        Module._free(ptr);
        const error = Module.UTF8ToString(Module._llama_get_error());
        throw new Error(`Failed to load model: ${error}`);
    }
    
    // Create context
    ctx = Module._llama_create_context(model);
    if (!ctx) {
        Module._llama_free_model(model);
        model = null;
        throw new Error('Failed to create context');
    }
    
    // Get model info
    const info = getModelInfo();
    
    return {
        success: true,
        size: buffer.byteLength,
        info: info
    };
}

// Get model information
function getModelInfo() {
    if (!model) return null;
    
    // Call C function to get info struct
    const infoPtr = Module._llama_get_model_info_ptr(model);
    
    return {
        name: Module.UTF8ToString(Module.getValue(infoPtr, 'i32')),
        arch: Module.UTF8ToString(Module.getValue(infoPtr + 4, 'i32')),
        n_vocab: Module.getValue(infoPtr + 8, 'i32'),
        n_ctx: Module.getValue(infoPtr + 12, 'i32'),
        n_embd: Module.getValue(infoPtr + 16, 'i32'),
        n_layer: Module.getValue(infoPtr + 20, 'i32'),
        n_head: Module.getValue(infoPtr + 24, 'i32'),
        n_head_kv: Module.getValue(infoPtr + 28, 'i32')
    };
}

// Generate text
function generate(prompt, params = {}) {
    if (!ctx) {
        throw new Error('Model not loaded');
    }
    
    aborted = false;
    
    const {
        maxTokens = 256,
        temperature = 0.7,
        topP = 0.9,
        topK = 40,
        repeatPenalty = 1.1,
        seed = 0,
        stream = true
    } = params;
    
    // Allocate prompt string
    const promptPtr = Module.allocateUTF8(prompt);
    
    // Create params struct
    const paramsPtr = Module._malloc(32);
    Module.setValue(paramsPtr + 0, maxTokens, 'i32');
    Module.setValue(paramsPtr + 4, temperature, 'float');
    Module.setValue(paramsPtr + 8, topP, 'float');
    Module.setValue(paramsPtr + 12, topK, 'i32');
    Module.setValue(paramsPtr + 16, repeatPenalty, 'float');
    Module.setValue(paramsPtr + 20, seed, 'i64');
    
    let totalTokens = 0;
    const startTime = performance.now();
    
    if (stream) {
        // Set up streaming callback
        Module._set_token_callback(Module.addFunction((textPtr) => {
            if (aborted) return;
            
            const text = Module.UTF8ToString(textPtr);
            totalTokens++;
            
            self.postMessage({
                type: 'token',
                data: {
                    text: text,
                    tokenCount: totalTokens
                }
            });
        }, 'vi'));
        
        // Generate with streaming
        Module._llama_generate_stream(ctx, promptPtr, paramsPtr, 0, 0);
    } else {
        // Generate blocking
        const resultPtr = Module._llama_generate(ctx, promptPtr, paramsPtr);
        const result = Module.UTF8ToString(resultPtr);
        Module._llama_free_string(resultPtr);
        
        self.postMessage({
            type: 'result',
            data: { text: result }
        });
    }
    
    // Cleanup
    Module._free(promptPtr);
    Module._free(paramsPtr);
    
    const elapsed = performance.now() - startTime;
    
    return {
        totalTokens: totalTokens,
        elapsed: elapsed,
        tokensPerSecond: totalTokens / (elapsed / 1000)
    };
}

// Clear conversation context
function clearContext() {
    if (ctx) {
        Module._llama_clear_context(ctx);
    }
}

// Abort generation
function abort() {
    aborted = true;
    if (ctx) {
        Module._llama_abort(ctx);
    }
}

// Message handler
self.onmessage = async (e) => {
    const { type, data, id } = e.data;
    
    try {
        let result;
        
        switch (type) {
            case 'init':
                await init();
                self.postMessage({ type: 'ready', id });
                break;
                
            case 'load':
                // data can be URL string or ArrayBuffer
                let buffer;
                if (typeof data.model === 'string') {
                    // Fetch from URL
                    self.postMessage({ type: 'status', id, data: 'Downloading model...' });
                    const response = await fetch(data.model);
                    
                    if (!response.ok) {
                        throw new Error(`Failed to fetch model: ${response.status}`);
                    }
                    
                    const total = parseInt(response.headers.get('content-length') || '0');
                    const reader = response.body.getReader();
                    const chunks = [];
                    let loaded = 0;
                    
                    while (true) {
                        const { done, value } = await reader.read();
                        if (done) break;
                        
                        chunks.push(value);
                        loaded += value.length;
                        
                        if (total > 0) {
                            self.postMessage({
                                type: 'progress',
                                id,
                                data: { loaded, total, percent: Math.round(loaded / total * 100) }
                            });
                        }
                    }
                    
                    buffer = new Uint8Array(loaded);
                    let offset = 0;
                    for (const chunk of chunks) {
                        buffer.set(chunk, offset);
                        offset += chunk.length;
                    }
                    buffer = buffer.buffer;
                } else {
                    buffer = data.model;
                }
                
                self.postMessage({ type: 'status', id, data: 'Loading model...' });
                result = await loadModel(buffer, data.contextSize || 0);
                self.postMessage({ type: 'loaded', id, data: result });
                break;
                
            case 'generate':
                const stats = generate(data.prompt, data.params);
                self.postMessage({ type: 'done', id, data: stats });
                break;
                
            case 'clear':
                clearContext();
                self.postMessage({ type: 'cleared', id });
                break;
                
            case 'abort':
                abort();
                self.postMessage({ type: 'aborted', id });
                break;
                
            case 'info':
                result = getModelInfo();
                self.postMessage({ type: 'info', id, data: result });
                break;
                
            default:
                throw new Error(`Unknown message type: ${type}`);
        }
    } catch (error) {
        self.postMessage({
            type: 'error',
            id,
            data: error.message || String(error)
        });
    }
};

// Report ready
self.postMessage({ type: 'worker_ready' });
