#!/usr/bin/env python3
"""
Initialize a new language project under /home/ubuntu/skills/<language-name>/.

Usage:
    python init_language.py <language-name>

Creates:
    /home/ubuntu/skills/<language-name>/
    ├── LANG.md           - Language specification (frontmatter + body)
    ├── generators/       - Code generators, compiler/interpreter stubs
    │   └── parser.py     - Skeleton PEG/recursive-descent parser
    ├── specifications/   - Formal grammar, type system rules
    │   └── grammar.ebnf  - EBNF grammar template
    └── syntax_templates/ - Example programs, standard library stubs
        └── hello.lang    - Hello-world example
"""

import os
import sys
import textwrap


def init_language(name: str) -> None:
    base = f"/home/ubuntu/skills/{name}"
    if os.path.exists(base):
        print(f"⚠️  Directory already exists: {base}")
        print("   Skipping initialization. Delete the directory first to re-init.")
        return

    dirs = [
        base,
        f"{base}/generators",
        f"{base}/specifications",
        f"{base}/syntax_templates",
    ]
    for d in dirs:
        os.makedirs(d, exist_ok=True)
        print(f"✅ Created directory: {d}")

    # --- LANG.md ---
    lang_md = textwrap.dedent(f"""\
    ---
    name: {name}
    description: "[TODO: Describe the language and when to use it.]"
    ---

    # {name.replace('-', ' ').title()}

    ## Overview

    [TODO: 1-2 sentences describing the language's purpose and domain.]

    ## Lexicon (Keywords & Operators)

    [TODO: List all keywords, operators, and reserved words.]

    ## Grammar (Syntax Rules)

    See `specifications/grammar.ebnf` for the formal EBNF grammar.

    ## Semantics

    [TODO: Describe the evaluation model, type system, and runtime behavior.]

    ## Examples

    See `syntax_templates/hello.{name}` for a hello-world example.
    """)
    with open(f"{base}/LANG.md", "w") as f:
        f.write(lang_md)
    print(f"✅ Created LANG.md")

    # --- grammar.ebnf ---
    grammar = textwrap.dedent(f"""\
    (* {name} Grammar — EBNF *)
    (* Generated by language-creator *)

    program     = {{ statement }} ;
    statement   = expression , ";" ;
    expression  = term , {{ ("+" | "-") , term }} ;
    term        = factor , {{ ("*" | "/") , factor }} ;
    factor      = NUMBER | IDENTIFIER | "(" , expression , ")" ;

    (* Tokens *)
    NUMBER      = digit , {{ digit }} ;
    IDENTIFIER  = letter , {{ letter | digit | "_" }} ;
    digit       = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
    letter      = "a" | ... | "z" | "A" | ... | "Z" ;
    """)
    with open(f"{base}/specifications/grammar.ebnf", "w") as f:
        f.write(grammar)
    print(f"✅ Created specifications/grammar.ebnf")

    # --- parser.py ---
    parser = textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"
    Skeleton recursive-descent parser for {name}.
    Reads source code and produces a simple AST (nested dicts).

    Usage:
        python parser.py <source-file>
    \"\"\"

    import sys
    import re
    from typing import Any


    # --- Lexer ---
    TOKEN_SPEC = [
        ("COMMENT",  r"\\(\\*.*?\\*\\)"),
        ("NUMBER",   r"\\d+"),
        ("IDENT",    r"[A-Za-z_][A-Za-z0-9_]*"),
        ("OP",       r"[+\\-*/]"),
        ("LPAREN",   r"\\("),
        ("RPAREN",   r"\\)"),
        ("SEMI",     r";"),
        ("SKIP",     r"[ \\t\\n]+"),
        ("MISMATCH", r"."),
    ]
    TOKEN_RE = re.compile("|".join(f"(?P<{{name}}>{{pat}})" for name, pat in TOKEN_SPEC))


    def tokenize(source: str) -> list[dict]:
        tokens = []
        for m in TOKEN_RE.finditer(source):
            kind = m.lastgroup
            value = m.group()
            if kind in ("SKIP", "COMMENT"):
                continue
            if kind == "MISMATCH":
                raise SyntaxError(f"Unexpected character: {{value!r}}")
            tokens.append({{"type": kind, "value": value}})
        return tokens


    # --- Parser ---
    class Parser:
        def __init__(self, tokens: list[dict]):
            self.tokens = tokens
            self.pos = 0

        def peek(self) -> dict | None:
            return self.tokens[self.pos] if self.pos < len(self.tokens) else None

        def consume(self, expected_type: str | None = None) -> dict:
            tok = self.peek()
            if tok is None:
                raise SyntaxError("Unexpected end of input")
            if expected_type and tok["type"] != expected_type:
                raise SyntaxError(f"Expected {{expected_type}}, got {{tok['type']}}")
            self.pos += 1
            return tok

        def parse_program(self) -> dict:
            stmts = []
            while self.peek() is not None:
                stmts.append(self.parse_statement())
            return {{"type": "Program", "body": stmts}}

        def parse_statement(self) -> dict:
            expr = self.parse_expression()
            self.consume("SEMI")
            return {{"type": "ExpressionStatement", "expression": expr}}

        def parse_expression(self) -> dict:
            left = self.parse_term()
            while self.peek() and self.peek()["type"] == "OP" and self.peek()["value"] in "+-":
                op = self.consume("OP")["value"]
                right = self.parse_term()
                left = {{"type": "BinaryExpr", "op": op, "left": left, "right": right}}
            return left

        def parse_term(self) -> dict:
            left = self.parse_factor()
            while self.peek() and self.peek()["type"] == "OP" and self.peek()["value"] in "*/":
                op = self.consume("OP")["value"]
                right = self.parse_factor()
                left = {{"type": "BinaryExpr", "op": op, "left": left, "right": right}}
            return left

        def parse_factor(self) -> dict:
            tok = self.peek()
            if tok["type"] == "NUMBER":
                self.consume()
                return {{"type": "NumberLiteral", "value": int(tok["value"])}}
            elif tok["type"] == "IDENT":
                self.consume()
                return {{"type": "Identifier", "name": tok["value"]}}
            elif tok["type"] == "LPAREN":
                self.consume("LPAREN")
                expr = self.parse_expression()
                self.consume("RPAREN")
                return expr
            else:
                raise SyntaxError(f"Unexpected token: {{tok}}")


    # --- Main ---
    if __name__ == "__main__":
        if len(sys.argv) < 2:
            print(f"Usage: python parser.py <source-file>")
            sys.exit(1)
        with open(sys.argv[1]) as f:
            source = f.read()
        tokens = tokenize(source)
        parser = Parser(tokens)
        ast = parser.parse_program()
        import json
        print(json.dumps(ast, indent=2))
    """)
    with open(f"{base}/generators/parser.py", "w") as f:
        f.write(parser)
    print(f"✅ Created generators/parser.py")

    # --- hello.lang ---
    hello = textwrap.dedent(f"""\
    (* Hello World in {name} *)
    1 + 2 * 3;
    (4 + 5) * 6;
    """)
    with open(f"{base}/syntax_templates/hello.{name}", "w") as f:
        f.write(hello)
    print(f"✅ Created syntax_templates/hello.{name}")

    print(f"\n🚀 Language '{name}' initialized at {base}")
    print("Next steps:")
    print("  1. Edit LANG.md to define the language specification")
    print("  2. Edit specifications/grammar.ebnf for the formal grammar")
    print("  3. Extend generators/parser.py for full language support")
    print("  4. Add example programs in syntax_templates/")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python init_language.py <language-name>")
        sys.exit(1)
    init_language(sys.argv[1])
