#!/usr/bin/env python3
"""
Plan 9 File Server Cluster Configurator

Generates all configuration files for a Plan 9 file server + N CPU server cluster
with cognitive namespace exports. Integrates with plan9-devcontainer and
plan9-cognitive-devkernel.

Composition:
  plan9-devcontainer(plan9-cognitive-devkernel[{{file-server}}])

Usage:
  python configure_cluster.py init <project_path> [--cpus N] [--domain NAME] [--subnet CIDR]
  python configure_cluster.py validate <project_path>
  python configure_cluster.py status
"""

import argparse
import json
import os
import sys
import textwrap
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Optional


# =============================================================================
# Cluster Model
# =============================================================================

@dataclass
class NodeConfig:
    """A single node in the Plan 9 cluster."""
    sysname: str
    role: str  # "file-server", "cpu-server", "auth-server"
    ip: str
    ether: str = "xx:xx:xx:xx:xx:xx"
    auth: str = ""
    authdom: str = ""
    fs: str = ""
    cpu: str = ""
    ports: list = field(default_factory=list)

    @property
    def dom(self) -> str:
        return f"{self.sysname}.{self.authdom}"


@dataclass
class ClusterConfig:
    """Full Plan 9 cluster configuration."""
    domain: str = "coglab"
    subnet: str = "192.168.1.0"
    netmask: str = "255.255.255.0"
    gateway: str = "192.168.1.1"
    dns: str = "192.168.1.1"
    fs_ip: str = "192.168.1.10"
    cpu_base_ip: int = 11
    num_cpus: int = 2
    filesystem: str = "hjfs"  # hjfs (9front) or cwfs (classic)
    cognitive_ns: bool = True
    cognitive_port: int = 5640

    @property
    def fs_node(self) -> NodeConfig:
        return NodeConfig(
            sysname="fs",
            role="file-server",
            ip=self.fs_ip,
            auth=f"fs.{self.domain}",
            authdom=self.domain,
            ports=[564, 567, 17010, 17013],
        )

    @property
    def cpu_nodes(self) -> list[NodeConfig]:
        nodes = []
        for i in range(self.num_cpus):
            ip = f"{self.subnet.rsplit('.', 1)[0]}.{self.cpu_base_ip + i}"
            nodes.append(NodeConfig(
                sysname=f"cpu{i+1}",
                role="cpu-server",
                ip=ip,
                auth=f"fs.{self.domain}",
                authdom=self.domain,
                fs=f"fs.{self.domain}",
                cpu=f"cpu{i+1}.{self.domain}",
                ports=[564, 17010, 17013],
            ))
        return nodes

    @property
    def all_nodes(self) -> list[NodeConfig]:
        return [self.fs_node] + self.cpu_nodes


# =============================================================================
# Configuration Generators
# =============================================================================

def gen_ndb_local(cfg: ClusterConfig) -> str:
    """Generate /lib/ndb/local network database."""
    lines = [
        f"# Plan 9 Cluster Network Database",
        f"# Generated by plan9-file-server skill",
        f"# Domain: {cfg.domain}  Subnet: {cfg.subnet}/{cfg.netmask}",
        f"",
        f"ipnet={cfg.domain} ip={cfg.subnet} ipmask={cfg.netmask}",
        f"    ipgw={cfg.gateway}",
        f"    dns={cfg.dns}",
        f"",
    ]
    for node in cfg.all_nodes:
        lines.append(f"# {node.role}: {node.sysname}")
        lines.append(f"sys={node.sysname}")
        lines.append(f"    dom={node.sysname}.{cfg.domain}")
        lines.append(f"    ip={node.ip}")
        lines.append(f"    ether={node.ether}")
        lines.append(f"    auth=fs.{cfg.domain}")
        lines.append(f"    authdom={cfg.domain}")
        if node.role == "cpu-server":
            lines.append(f"    fs=fs.{cfg.domain}")
            lines.append(f"    cpu={node.sysname}.{cfg.domain}")
        lines.append("")
    return "\n".join(lines)


def gen_cpurc_fs(cfg: ClusterConfig) -> str:
    """Generate /cfg/fs/cpurc for the file server."""
    cog_section = ""
    if cfg.cognitive_ns:
        cog_section = textwrap.dedent(f"""\

        # Cognitive namespace exports (plan9-cognitive-devkernel)
        # Start AtomSpace 9P file server on port {cfg.cognitive_port}
        if(test -x /bin/atomspace-9p-server)
            atomspace-9p-server -p {cfg.cognitive_port} &

        # Export cognitive namespace to all CPU servers
        aux/listen1 -t tcp!*!{cfg.cognitive_port} /bin/exportfs -r /cognitive &
        """)

    return textwrap.dedent(f"""\
    #!/bin/rc
    # File Server + Auth Server startup
    # Generated by plan9-file-server skill
    # Cluster domain: {cfg.domain}

    sysname=fs
    authdom={cfg.domain}

    # Authentication services
    auth/keyfs
    auth/cron >>/sys/log/cron 2>&1 &

    # Network configuration
    ip/ipconfig -g {cfg.gateway} ether /net/ether0 \\
                {cfg.fs_ip} {cfg.netmask}

    # Mount file system ({cfg.filesystem})
    srv -A {cfg.filesystem} {cfg.filesystem}.cmd
    mount -c /srv/{cfg.filesystem} /n/{cfg.filesystem}
    mount -bc /srv/{cfg.filesystem} /
    disk/kfscmd -n {cfg.filesystem}.cmd 'allow'

    # Network services
    aux/listen1 -t tcp!*!564 /bin/exportfs -a &
    aux/listen1 -t tcp!*!17010 /bin/cpu -R &
    aux/listen1 -t tcp!*!17013 /bin/exportfs -R &

    # Auth listener
    aux/listen -q -t /rc/bin/service.auth \\
                  -d /rc/bin/service tcp
    {cog_section}
    echo 'File server fs.{cfg.domain} ready'
    """)


def gen_cpurc_cpu(cfg: ClusterConfig, node: NodeConfig) -> str:
    """Generate /cfg/<sysname>/cpurc for a CPU server."""
    cog_section = ""
    if cfg.cognitive_ns:
        cog_section = textwrap.dedent(f"""\

        # Mount cognitive namespace from file server
        srv tcp!fs.{cfg.domain}!{cfg.cognitive_port} cogfs
        mount /srv/cogfs /cognitive

        # Start local cognitive services
        if(test -x /bin/pln-server)
            pln-server -p {cfg.cognitive_port + 1} &

        # Export local cognitive results
        aux/listen1 -t tcp!*!{cfg.cognitive_port + 1} /bin/exportfs -r /cognitive &
        """)

    return textwrap.dedent(f"""\
    #!/bin/rc
    # CPU Server startup: {node.sysname}
    # Generated by plan9-file-server skill
    # Cluster domain: {cfg.domain}

    sysname={node.sysname}
    authdom={cfg.domain}

    # Network configuration
    ip/ipconfig -g {cfg.gateway} ether /net/ether0 \\
                {node.ip} {cfg.netmask}

    # Mount file server
    srv -n tcp!fs.{cfg.domain}!564 fscons
    mount -c /srv/fscons /n/fs
    bind -ac /n/fs /

    # CPU services
    aux/listen1 -t tcp!*!17010 /bin/cpu -R &
    aux/listen1 -t tcp!*!17013 /bin/exportfs -R &
    {cog_section}
    echo 'CPU server {node.sysname}.{cfg.domain} ready'
    """)


def gen_plan9ini_fs(cfg: ClusterConfig) -> str:
    """Generate plan9.ini for the file server."""
    return textwrap.dedent(f"""\
    # File Server plan9.ini
    # Generated by plan9-file-server skill
    bootfile=9pccpuf
    service=cpu
    auth=fs.{cfg.domain}
    authdom={cfg.domain}
    """)


def gen_plan9ini_cpu(cfg: ClusterConfig, node: NodeConfig) -> str:
    """Generate plan9.ini for a CPU server."""
    return textwrap.dedent(f"""\
    # CPU Server plan9.ini: {node.sysname}
    # Generated by plan9-file-server skill
    bootfile=9pccpuf
    service=cpu
    auth=fs.{cfg.domain}
    authdom={cfg.domain}
    fs=fs.{cfg.domain}
    cpu={node.sysname}.{cfg.domain}
    """)


def gen_docker_compose(cfg: ClusterConfig) -> str:
    """Generate docker-compose.fileserver.yml with dedicated file server."""
    cpu_ports = ""
    for i, node in enumerate(cfg.cpu_nodes):
        cpu_ports += f"      # {node.sysname}: port {565+i}\n"

    cog_env = ""
    cog_ports = ""
    if cfg.cognitive_ns:
        cog_env = f"      - PLAN9_COGNITIVE_PORT={cfg.cognitive_port}\n"
        cog_ports = f'      - "{cfg.cognitive_port}:{cfg.cognitive_port}"\n'

    return textwrap.dedent(f"""\
    # =============================================================================
    # Plan 9 File Server Cluster — Docker Compose (QEMU-based)
    # File server + Auth server + N CPU servers + Cognitive namespace
    # Generated by plan9-file-server skill
    # =============================================================================
    #
    # Usage:
    #   docker compose -f docker-compose.fileserver.yml up -d
    #   docker compose -f docker-compose.fileserver.yml --scale plan9-cpu={cfg.num_cpus} up -d
    #

    services:
      # --------------------------------------------------------------------------
      # File Server + Auth Server (fs) — Storage, authentication, coordination
      # --------------------------------------------------------------------------
      plan9-fileserver:
        build:
          context: .
          dockerfile: .plan9-devenv/Dockerfile
        container_name: plan9-fileserver
        hostname: plan9-fileserver
        environment:
          - PLAN9=/usr/local/plan9
          - PLAN9_NODE_ID=0
          - PLAN9_NODE_ROLE=file-server
          - PLAN9_9P_PORT=564
          - PLAN9_AUTH_PORT=567
          - PLAN9_FS_TYPE={cfg.filesystem}
          - PLAN9_DOMAIN={cfg.domain}
          - PLAN9_IMG=/var/plan9/9front.qcow2
    {cog_env}    ports:
          - "564:564"
          - "567:567"
          - "17010:17010"
          - "17013:17013"
          - "8080:8080"
    {cog_ports}    volumes:
          - plan9-fs-data:/var/plan9/data
          - plan9-fs-fossil:/var/plan9/fossil
          - ./:/workspace
        networks:
          plan9-net:
            ipv4_address: 172.29.0.10
            aliases:
              - fs.{cfg.domain}
              - auth.{cfg.domain}
        command: >
          qemu-system-x86_64 -nographic -m 2G
          -drive file=/var/plan9/9front.qcow2,format=qcow2
          -drive file=/var/plan9/fossil/fs.qcow2,format=qcow2,if=virtio
          -net nic -net user,hostfwd=tcp::564-:564,hostfwd=tcp::567-:567,hostfwd=tcp::17010-:17010,hostfwd=tcp::8080-:8080
          -append "console=0 nomp service=cpu"
        healthcheck:
          test: ["CMD", "bash", "-c", "echo | socat - TCP:localhost:564,connect-timeout=2"]
          interval: 10s
          timeout: 5s
          retries: 5

      # --------------------------------------------------------------------------
      # CPU Server Nodes — Distributed cognitive processing
      # --------------------------------------------------------------------------
      plan9-cpu:
        build:
          context: .
          dockerfile: .plan9-devenv/Dockerfile
        environment:
          - PLAN9=/usr/local/plan9
          - PLAN9_NODE_ROLE=cpu-server
          - PLAN9_FILESERVER=tcp!plan9-fileserver!564
          - PLAN9_AUTH=tcp!plan9-fileserver!567
          - PLAN9_DOMAIN={cfg.domain}
        volumes:
          - ./:/workspace
        networks:
          - plan9-net
        depends_on:
          plan9-fileserver:
            condition: service_healthy
        command: >
          qemu-system-x86_64 -nographic -m 1G
          -drive file=/var/plan9/9front.qcow2,format=qcow2
          -net nic -net user,hostfwd=tcp::565-:564
          -append "console=0 nomp service=cpu"
        deploy:
          replicas: {cfg.num_cpus}
          resources:
            limits:
              cpus: "2"
              memory: 2G

      # --------------------------------------------------------------------------
      # Grid Monitor — Web dashboard
      # --------------------------------------------------------------------------
      plan9-monitor:
        build:
          context: .
          dockerfile: .plan9-devenv/Dockerfile
        container_name: plan9-monitor
        hostname: plan9-monitor
        environment:
          - PLAN9=/usr/local/plan9
          - PLAN9_NODE_ROLE=stat-server
          - FLASK_APP=/workspace/scripts/grid_monitor.py
          - PLAN9_GRID_NODES={cfg.num_cpus + 1}
        ports:
          - "9090:9090"
        volumes:
          - ./:/workspace
        networks:
          - plan9-net
        depends_on:
          plan9-fileserver:
            condition: service_healthy
        command: >
          python3 /workspace/scripts/grid_monitor.py

    volumes:
      plan9-fs-data:
      plan9-fs-fossil:

    networks:
      plan9-net:
        driver: bridge
        ipam:
          config:
            - subnet: 172.29.0.0/16
    """)


def gen_cognitive_exports_rc(cfg: ClusterConfig) -> str:
    """Generate cognitive namespace export script for file server."""
    return textwrap.dedent(f"""\
    #!/bin/rc
    # Cognitive Namespace Export Script
    # Run on file server to export /cognitive/ to all CPU servers
    # Generated by plan9-file-server skill
    #
    # Composition: plan9-cognitive-devkernel[{{{{file-server}}}}]

    # Create cognitive namespace directories
    mkdir -p /cognitive/atomspace/atoms
    mkdir -p /cognitive/atomspace/types
    mkdir -p /cognitive/atomspace/indices
    mkdir -p /cognitive/inference/rules
    mkdir -p /cognitive/inference/queue
    mkdir -p /cognitive/inference/results
    mkdir -p /cognitive/attention/bank
    mkdir -p /cognitive/attention/agents
    mkdir -p /cognitive/learning/populations
    mkdir -p /cognitive/learning/fitness
    mkdir -p /cognitive/temporal/levels
    mkdir -p /cognitive/temporal/phases
    mkdir -p /cognitive/autognosis/images
    mkdir -p /cognitive/autognosis/insights
    mkdir -p /cognitive/autognosis/metrics

    # Export cognitive namespace via 9P2000
    aux/listen1 -t tcp!*!{cfg.cognitive_port} /bin/exportfs -r /cognitive &

    echo 'Cognitive namespace exported on port {cfg.cognitive_port}'
    echo 'CPU servers can mount with:'
    echo '  srv tcp!fs.{cfg.domain}!{cfg.cognitive_port} cogfs'
    echo '  mount /srv/cogfs /cognitive'
    """)


def gen_union_atomspace_rc(cfg: ClusterConfig) -> str:
    """Generate script to union-mount AtomSpace from all CPU servers."""
    hosts = " ".join(f"cpu{i+1}.{cfg.domain}" for i in range(cfg.num_cpus))
    return textwrap.dedent(f"""\
    #!/bin/rc
    # Union AtomSpace — Mount and bind AtomSpace from all CPU servers
    # Creates a unified view of distributed atoms at /cognitive/atomspace
    # Generated by plan9-file-server skill

    hosts=({hosts})

    for(host in $hosts) {{
        echo 'Importing AtomSpace from '$host'...'
        srv tcp!$host!{cfg.cognitive_port + 1} $host^-cogfs
        mount /srv/$host^-cogfs /mnt/$host/cognitive
        bind -a /mnt/$host/cognitive/atomspace /cognitive/atomspace
    }}

    echo 'Union AtomSpace mounted. Atoms from all CPU servers visible at:'
    echo '  /cognitive/atomspace/'
    ls /cognitive/atomspace/atoms
    """)


# =============================================================================
# Validation
# =============================================================================

CLUSTER_PROMISES = [
    ("file-server",      "File server node configured (cpurc, plan9.ini, ndb)"),
    ("auth-server",      "Auth services enabled (keyfs, faktotum, tcp567)"),
    ("ndb-config",       "Network database has all nodes defined"),
    ("cpu-mount",        "CPU servers reference file server for mount"),
    ("cognitive-export", "Cognitive namespace exported via 9P2000"),
    ("docker-compose",   "docker-compose.fileserver.yml defines plan9-fileserver"),
    ("fs-storage",       "File system type configured (hjfs or cwfs)"),
    ("cluster-network",  "Cluster network subnet and gateway defined"),
]


def validate_cluster(project_path: str) -> list[dict]:
    """Validate a cluster configuration against file-server promises."""
    p = Path(project_path)
    results = []

    for name, desc in CLUSTER_PROMISES:
        satisfied = False
        evidence = ""

        if name == "file-server":
            cpurc = p / "cfg" / "fs" / "cpurc"
            if cpurc.exists():
                satisfied = True
                evidence = "cfg/fs/cpurc exists"
            elif (p / "templates" / "cfg" / "fs-cpurc.rc").exists():
                satisfied = True
                evidence = "templates/cfg/fs-cpurc.rc exists"

        elif name == "auth-server":
            for f in [p / "cfg" / "fs" / "cpurc", p / "templates" / "cfg" / "fs-cpurc.rc"]:
                if f.exists() and "keyfs" in f.read_text():
                    satisfied = True
                    evidence = f"auth/keyfs in {f.name}"
                    break

        elif name == "ndb-config":
            for f in [p / "lib" / "ndb" / "local", p / "templates" / "ndb-local.conf"]:
                if f.exists():
                    content = f.read_text()
                    if "sys=fs" in content and "sys=cpu" in content:
                        satisfied = True
                        evidence = f"File server and CPU nodes in {f.name}"
                        break

        elif name == "cpu-mount":
            for f in p.rglob("*cpurc*"):
                if f.is_file() and "mount" in f.read_text() and "fs" in f.read_text():
                    satisfied = True
                    evidence = f"File server mount in {f.name}"
                    break

        elif name == "cognitive-export":
            for f in p.rglob("*.rc"):
                if f.is_file() and "cognitive" in f.read_text() and "exportfs" in f.read_text():
                    satisfied = True
                    evidence = f"Cognitive export in {f.name}"
                    break
            if not satisfied:
                for f in p.rglob("*.yml"):
                    if f.is_file() and "COGNITIVE" in f.read_text().upper():
                        satisfied = True
                        evidence = f"Cognitive config in {f.name}"
                        break

        elif name == "docker-compose":
            dc = p / "docker-compose.fileserver.yml"
            if dc.exists() and "plan9-fileserver" in dc.read_text():
                satisfied = True
                evidence = "plan9-fileserver service in docker-compose.fileserver.yml"

        elif name == "fs-storage":
            for f in p.rglob("*"):
                if f.is_file() and f.suffix in [".rc", ".conf", ".yml", ".ini"]:
                    try:
                        content = f.read_text()
                        if "hjfs" in content or "cwfs" in content or "fossil" in content:
                            satisfied = True
                            evidence = f"File system type in {f.name}"
                            break
                    except Exception:
                        pass

        elif name == "cluster-network":
            for f in p.rglob("*"):
                if f.is_file() and f.suffix in [".conf", ""]:
                    try:
                        content = f.read_text()
                        if "ipnet=" in content or "subnet:" in content:
                            satisfied = True
                            evidence = f"Network config in {f.name}"
                            break
                    except Exception:
                        pass

        results.append({
            "name": name,
            "description": desc,
            "satisfied": satisfied,
            "evidence": evidence,
        })

    return results


# =============================================================================
# Init Command
# =============================================================================

def init_cluster(project_path: str, cfg: ClusterConfig):
    """Generate all cluster configuration files."""
    p = Path(project_path)
    p.mkdir(parents=True, exist_ok=True)

    # Templates directory
    tpl = p / "templates"
    tpl.mkdir(exist_ok=True)

    # ndb/local
    ndb_file = tpl / "ndb-local.conf"
    ndb_file.write_text(gen_ndb_local(cfg))
    print(f"  + {ndb_file}")

    # File server cpurc
    cfg_dir = tpl / "cfg"
    cfg_dir.mkdir(exist_ok=True)
    fs_cpurc = cfg_dir / "fs-cpurc.rc"
    fs_cpurc.write_text(gen_cpurc_fs(cfg))
    print(f"  + {fs_cpurc}")

    # File server plan9.ini
    fs_ini = cfg_dir / "fs-plan9.ini"
    fs_ini.write_text(gen_plan9ini_fs(cfg))
    print(f"  + {fs_ini}")

    # CPU server configs
    for node in cfg.cpu_nodes:
        cpu_cpurc = cfg_dir / f"{node.sysname}-cpurc.rc"
        cpu_cpurc.write_text(gen_cpurc_cpu(cfg, node))
        print(f"  + {cpu_cpurc}")

        cpu_ini = cfg_dir / f"{node.sysname}-plan9.ini"
        cpu_ini.write_text(gen_plan9ini_cpu(cfg, node))
        print(f"  + {cpu_ini}")

    # Docker compose
    dc_file = p / "docker-compose.fileserver.yml"
    dc_file.write_text(gen_docker_compose(cfg))
    print(f"  + {dc_file}")

    # Cognitive scripts
    if cfg.cognitive_ns:
        scripts_dir = tpl / "scripts"
        scripts_dir.mkdir(exist_ok=True)

        cog_export = scripts_dir / "cognitive-export.rc"
        cog_export.write_text(gen_cognitive_exports_rc(cfg))
        print(f"  + {cog_export}")

        union_as = scripts_dir / "union-atomspace.rc"
        union_as.write_text(gen_union_atomspace_rc(cfg))
        print(f"  + {union_as}")

    # Cluster config JSON
    config_file = p / "cluster.json"
    config_file.write_text(json.dumps(asdict(cfg), indent=2) + "\n")
    print(f"  + {config_file}")

    print(f"\n  Cluster configured: 1 file server + {cfg.num_cpus} CPU servers")
    print(f"  Domain: {cfg.domain}  Subnet: {cfg.subnet}/{cfg.netmask}")


# =============================================================================
# CLI
# =============================================================================

BANNER = """
+==============================================================+
|  Plan 9 File Server Cluster Configurator                      |
|  plan9-devcontainer(plan9-cognitive-devkernel[file-server])    |
+==============================================================+
"""


def main():
    parser = argparse.ArgumentParser(description="Plan 9 File Server Cluster Configurator")
    sub = parser.add_subparsers(dest="command")

    # init
    p_init = sub.add_parser("init", help="Initialize cluster configuration")
    p_init.add_argument("project_path", help="Project directory")
    p_init.add_argument("--cpus", type=int, default=2, help="Number of CPU servers (default: 2)")
    p_init.add_argument("--domain", default="coglab", help="Auth domain name (default: coglab)")
    p_init.add_argument("--subnet", default="192.168.1.0", help="Subnet (default: 192.168.1.0)")
    p_init.add_argument("--filesystem", default="hjfs", choices=["hjfs", "cwfs"],
                        help="File system type (default: hjfs)")
    p_init.add_argument("--no-cognitive", action="store_true", help="Disable cognitive namespace")

    # validate
    p_val = sub.add_parser("validate", help="Validate cluster configuration")
    p_val.add_argument("project_path", help="Project directory")

    # status
    sub.add_parser("status", help="Show cluster status")

    args = parser.parse_args()

    if args.command == "init":
        print(BANNER)
        print(f"  Initializing Plan 9 cluster at: {args.project_path}")
        print()
        cfg = ClusterConfig(
            domain=args.domain,
            subnet=args.subnet,
            num_cpus=args.cpus,
            filesystem=args.filesystem,
            cognitive_ns=not args.no_cognitive,
        )
        init_cluster(args.project_path, cfg)

    elif args.command == "validate":
        print(BANNER)
        print(f"  Validating cluster at: {args.project_path}")
        print()
        results = validate_cluster(args.project_path)
        for r in results:
            icon = "+" if r["satisfied"] else "X"
            print(f"  {icon} {r['name']}: {r['description']}")
            if r["evidence"]:
                print(f"       Evidence: {r['evidence']}")
        satisfied = sum(1 for r in results if r["satisfied"])
        total = len(results)
        print()
        if satisfied == total:
            print(f"  + All {total} cluster promises satisfied.")
        else:
            print(f"  X {satisfied}/{total} cluster promises satisfied.")

    elif args.command == "status":
        print(BANNER)
        print("  File Server Cluster Promises:")
        print()
        for name, desc in CLUSTER_PROMISES:
            print(f"    {name:20s} — {desc}")

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
