#!/usr/bin/env python3
"""
Seed Grammar Emitter for Topology Weaver
Generates BNF-style grammars from topology specifications for pattern evolution.
"""

import sys
import json
import argparse
from pathlib import Path
from typing import List, Dict, Set
import yaml


class GrammarEmitter:
    """Emit seed grammars from topology specifications."""
    
    def __init__(self):
        self.topology = None
        self.tags: Set[str] = set()
        self.components: Set[str] = set()
        self.integration_points: Set[str] = set()
    
    def load_topology(self, filepath: str):
        """Load topology from YAML or JSON file."""
        path = Path(filepath)
        with open(path) as f:
            if path.suffix in ['.yaml', '.yml']:
                self.topology = yaml.safe_load(f)
            else:
                self.topology = json.load(f)
        
        self._extract_symbols()
    
    def _extract_symbols(self):
        """Extract grammar symbols from topology."""
        if not self.topology:
            return
        
        # Extract global tags
        for tag in self.topology.get('global_tags', []):
            self.tags.add(tag['name'])
        
        # Extract from MLP blocks
        for block in self.topology.get('mlp_blocks', []):
            for component in block.get('components', []):
                self.components.add(component['component_type'])
                if component.get('tag'):
                    self.tags.add(component['tag']['name'])
            
            for ip in block.get('integration_points', []):
                self.integration_points.add(ip['point_type'])
                if ip.get('tag'):
                    self.tags.add(ip['tag']['name'])
        
        # Extract meshwork anchors
        for anchor in self.topology.get('meshwork_anchors', []):
            self.integration_points.add(anchor['point_type'])
            if anchor.get('tag'):
                self.tags.add(anchor['tag']['name'])
    
    def emit_bnf(self) -> str:
        """Emit BNF grammar."""
        lines = [
            "# Seed Grammar for Topology Evolution",
            "# Generated by Topology Weaver",
            f"# Architecture: {self.topology.get('architecture', 'unknown')}",
            "",
            "# === TOPOLOGY STRUCTURE ===",
            "",
            "<topology> ::= <metadata> <layer>+",
            "",
            "<metadata> ::= <name> <architecture> <dimensions>",
            "<name> ::= IDENTIFIER",
            "<architecture> ::= \"gpt2\" | \"gpt2-medium\" | \"gpt2-large\" | \"gpt2-xl\"",
            "<dimensions> ::= <d_model> <n_layers>",
            "<d_model> ::= INTEGER",
            "<n_layers> ::= INTEGER",
            "",
            "# === LAYER STRUCTURE ===",
            "",
            "<layer> ::= <attention_block> <mlp_block>",
            "",
            "# === ATTENTION BLOCK ===",
            "",
            "<attention_block> ::= <meshwork_anchor> <attention_head>+ <meshwork_anchor>",
            "<attention_head> ::= <query_projection> <key_projection> <value_projection> <output_projection>",
            "<query_projection> ::= <linear> <tag>",
            "<key_projection> ::= <linear> <tag>",
            "<value_projection> ::= <linear> <tag>",
            "<output_projection> ::= <linear> <tag>",
            "",
            "# === MLP BLOCK ===",
            "",
            "<mlp_block> ::= <integration_point> <projection> <activation> <projection> <integration_point>",
            "<projection> ::= <linear> <tag>",
            "<linear> ::= \"Linear\" \"(\" <input_dim> \",\" <output_dim> \")\"",
            "<input_dim> ::= INTEGER | <dimension_expr>",
            "<output_dim> ::= INTEGER | <dimension_expr>",
            "<dimension_expr> ::= <d_model> | <d_model> \"*\" INTEGER",
            "",
            "# === ACTIVATION FUNCTIONS ===",
            "",
            "<activation> ::= <gelu> | <relu> | <silu> | <custom_activation>",
            "<gelu> ::= \"GELU\" <tag>",
            "<relu> ::= \"ReLU\" <tag>",
            "<silu> ::= \"SiLU\" <tag>",
            "<custom_activation> ::= IDENTIFIER <tag>",
            "",
            "# === INTEGRATION POINTS ===",
            "",
            "<integration_point> ::= <point_type> <connections> <tag>?",
            "<point_type> ::= " + " | ".join(f'"{pt}"' for pt in sorted(self.integration_points)) if self.integration_points else "<point_type> ::= \"wave_input\" | \"wave_output\" | \"superposition_state\"",
            "<connections> ::= \"[\" <connection> (\",\" <connection>)* \"]\"",
            "<connection> ::= IDENTIFIER",
            "",
            "# === MESHWORK ANCHORS ===",
            "",
            "<meshwork_anchor> ::= <anchor_type> <anchor_connections> <tag>?",
            "<anchor_type> ::= \"query_field\" | \"key_field\" | \"value_field\" | \"output_field\"",
            "<anchor_connections> ::= <connections>",
            "",
            "# === CONTEXTUAL TAGS ===",
            "",
            "<tag> ::= <builtin_tag> | <custom_tag>",
            "<builtin_tag> ::= " + " | ".join(f'"{tag}"' for tag in sorted(self.tags)) if self.tags else "<builtin_tag> ::= \"particle_creation\" | \"particle_annihilation\" | \"measurement_gate\"",
            "<custom_tag> ::= IDENTIFIER",
            "",
            "# === TERMINALS ===",
            "",
            "IDENTIFIER ::= [a-zA-Z_][a-zA-Z0-9_]*",
            "INTEGER ::= [0-9]+",
        ]
        
        return "\n".join(lines)
    
    def emit_ebnf(self) -> str:
        """Emit EBNF grammar (more readable)."""
        lines = [
            "(* Seed Grammar for Topology Evolution *)",
            f"(* Architecture: {self.topology.get('architecture', 'unknown')} *)",
            "",
            "(* Top-level structure *)",
            "topology = metadata, { layer } ;",
            "metadata = name, architecture, dimensions ;",
            "",
            "(* Layer composition *)",
            "layer = attention_block, mlp_block ;",
            "",
            "(* Attention block *)",
            "attention_block = meshwork_anchor, { attention_head }, meshwork_anchor ;",
            "attention_head = query_proj, key_proj, value_proj, output_proj ;",
            "",
            "(* MLP block *)",
            "mlp_block = integration_point, projection, activation, projection, integration_point ;",
            "projection = linear, [ tag ] ;",
            "linear = 'Linear', '(', dim, ',', dim, ')' ;",
            "",
            "(* Activation *)",
            "activation = ( 'GELU' | 'ReLU' | 'SiLU' | identifier ), [ tag ] ;",
            "",
            "(* Integration points *)",
            "integration_point = point_type, connections, [ tag ] ;",
            f"point_type = {' | '.join(repr(pt) for pt in sorted(self.integration_points))} ;" if self.integration_points else "point_type = 'wave_input' | 'wave_output' ;",
            "",
            "(* Tags *)",
            "tag = builtin_tag | custom_tag ;",
            f"builtin_tag = {' | '.join(repr(t) for t in sorted(self.tags))} ;" if self.tags else "builtin_tag = 'particle_creation' | 'measurement_gate' ;",
            "custom_tag = identifier ;",
        ]
        
        return "\n".join(lines)
    
    def emit_production_rules(self) -> str:
        """Emit production rules for topology evolution."""
        rules = [
            "# Production Rules for Topology Evolution",
            "# These rules define how topologies can be composed and mutated",
            "",
            "# === COMPOSITION RULES ===",
            "",
            "# Stack layers",
            "STACK: topology(n) + layer -> topology(n+1)",
            "",
            "# Parallel attention heads",
            "PARALLEL: attention_head * k -> multi_head_attention(k)",
            "",
            "# Residual connection",
            "RESIDUAL: block(x) -> x + block(x)",
            "",
            "# === MUTATION RULES ===",
            "",
            "# Tag substitution",
            "TAG_SUB: component[tag_a] -> component[tag_b]",
            "",
            "# Dimension scaling",
            "SCALE: linear(d_in, d_out) -> linear(d_in * k, d_out * k)",
            "",
            "# Activation swap",
            "ACT_SWAP: gelu -> silu | relu | custom",
            "",
            "# === INTEGRATION RULES ===",
            "",
            "# Connect meshwork",
            "MESH_CONNECT: anchor_a.output -> anchor_b.input",
            "",
            "# Branch flow",
            "BRANCH: integration_point -> [connection_1, connection_2, ...]",
            "",
            "# === VALIDATION RULES ===",
            "",
            "# Dimension consistency",
            "VALID_DIM: layer[i].output_dim == layer[i+1].input_dim",
            "",
            "# Tag consistency",
            "VALID_TAG: tag in (builtin_tags ∪ custom_tags)",
            "",
            "# Flow conservation",
            "VALID_FLOW: ∀ integration_point: inputs_connected ∧ outputs_connected",
        ]
        
        return "\n".join(rules)


def main():
    parser = argparse.ArgumentParser(
        description='Emit seed grammar from topology specification'
    )
    parser.add_argument(
        '--topology', '-t',
        required=True,
        help='Path to topology.yaml file'
    )
    parser.add_argument(
        '--output', '-o',
        default='grammar.bnf',
        help='Output file path (default: grammar.bnf)'
    )
    parser.add_argument(
        '--format', '-f',
        choices=['bnf', 'ebnf', 'rules', 'all'],
        default='bnf',
        help='Grammar format (default: bnf)'
    )
    
    args = parser.parse_args()
    
    emitter = GrammarEmitter()
    
    print(f"Loading topology from: {args.topology}")
    emitter.load_topology(args.topology)
    
    output_path = Path(args.output)
    
    if args.format == 'all':
        # Emit all formats
        base = output_path.stem
        
        with open(f"{base}.bnf", 'w') as f:
            f.write(emitter.emit_bnf())
        print(f"✓ BNF grammar written to: {base}.bnf")
        
        with open(f"{base}.ebnf", 'w') as f:
            f.write(emitter.emit_ebnf())
        print(f"✓ EBNF grammar written to: {base}.ebnf")
        
        with open(f"{base}.rules", 'w') as f:
            f.write(emitter.emit_production_rules())
        print(f"✓ Production rules written to: {base}.rules")
        
    else:
        # Emit single format
        if args.format == 'bnf':
            content = emitter.emit_bnf()
        elif args.format == 'ebnf':
            content = emitter.emit_ebnf()
        else:  # rules
            content = emitter.emit_production_rules()
        
        with open(output_path, 'w') as f:
            f.write(content)
        
        print(f"✓ Grammar written to: {args.output}")
    
    print(f"✓ Extracted {len(emitter.tags)} tags")
    print(f"✓ Extracted {len(emitter.components)} component types")
    print(f"✓ Extracted {len(emitter.integration_points)} integration point types")


if __name__ == "__main__":
    main()
