#!/usr/bin/env python3
"""
Generate unified client code from configuration files.

Usage:
    python generate_client.py --config <config-dir> --output <output-dir> --language <typescript|python>

Example:
    python generate_client.py --config ./config --output ./src --language typescript
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

import yaml


def load_config(config_dir: Path) -> Dict[str, Any]:
    """Load all YAML configuration files."""
    config = {}
    for yaml_file in config_dir.glob("*.yaml"):
        with open(yaml_file) as f:
            data = yaml.safe_load(f)
            if data:
                config.update(data)
    return config


def generate_typescript_types(config: Dict[str, Any], output_dir: Path) -> None:
    """Generate TypeScript type definitions."""
    entities = config.get("entities", {})
    
    types_content = '''/**
 * Auto-generated type definitions for multiplatform integration.
 * DO NOT EDIT - Generated by multiplatform-api-weaver
 */

// Pagination types
export interface PaginatedResponse<T> {
  data: T[];
  hasMore: boolean;
  cursor?: string;
  total?: number;
}

export interface PaginationParams {
  limit?: number;
  cursor?: string;
}

// Error types
export interface ApiError {
  code: string;
  message: string;
  platform: string;
  details?: Record<string, unknown>;
}

// Platform types
export type Platform = ''' + " | ".join(f'"{p}"' for p in config.get("platforms", {}).keys()) + ''';

'''
    
    # Generate entity types
    for entity_name, entity_config in entities.items():
        canonical_fields = entity_config.get("canonical_fields", [])
        type_name = entity_name.title().replace("_", "")
        
        types_content += f'''
// {type_name} entity
export interface {type_name} {{
'''
        for field in canonical_fields:
            field_type = "string"  # Default type
            if field in ["created_at", "updated_at"]:
                field_type = "Date | string"
            elif field in ["metadata", "line_items"]:
                field_type = "Record<string, unknown>"
            elif field.endswith("_quantity") or field == "total":
                field_type = "number"
            
            types_content += f"  {field}?: {field_type};\n"
        
        types_content += "}\n"
        
        # Generate create/update input types
        types_content += f'''
export interface Create{type_name}Input {{
'''
        for field in canonical_fields:
            if field not in ["id", "created_at", "updated_at"]:
                field_type = "string"
                if field in ["metadata"]:
                    field_type = "Record<string, unknown>"
                elif field.endswith("_quantity") or field == "total":
                    field_type = "number"
                types_content += f"  {field}?: {field_type};\n"
        types_content += "}\n"
    
    # Generate command types
    commands = config.get("commands", {})
    types_content += "\n// Command types\n"
    
    for cmd_name, cmd_config in commands.items():
        type_name = "".join(word.title() for word in cmd_name.replace(":", "_").split("_")) + "Args"
        args = cmd_config.get("args", [])
        
        types_content += f"\nexport interface {type_name} {{\n"
        for arg in args:
            arg_name = arg.get("name", "")
            arg_type = arg.get("type", "string")
            required = arg.get("required", False)
            
            ts_type = {
                "string": "string",
                "integer": "number",
                "boolean": "boolean",
                "array": "string[]"
            }.get(arg_type, "string")
            
            optional = "" if required else "?"
            types_content += f"  {arg_name}{optional}: {ts_type};\n"
        types_content += "}\n"
    
    (output_dir / "types.ts").write_text(types_content)
    print(f"   ✓ Generated types.ts")


def generate_typescript_client(config: Dict[str, Any], output_dir: Path) -> None:
    """Generate TypeScript unified client."""
    platforms = list(config.get("platforms", {}).keys())
    commands = config.get("commands", {})
    
    client_content = '''/**
 * Unified client for multiplatform API integration.
 * DO NOT EDIT - Generated by multiplatform-api-weaver
 */

import type { Platform, PaginatedResponse, PaginationParams, ApiError } from './types';

export interface ClientConfig {
  platforms: Record<Platform, PlatformConfig>;
  primaryPlatform?: Platform;
}

export interface PlatformConfig {
  baseUrl: string;
  auth: AuthConfig;
  rateLimit?: RateLimitConfig;
}

export interface AuthConfig {
  type: 'oauth2' | 'api_key' | 'token';
  token?: string;
  apiKey?: string;
  refreshToken?: string;
}

export interface RateLimitConfig {
  requests: number;
  period: string;
}

export interface RequestOptions {
  method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  body?: Record<string, unknown>;
  params?: Record<string, string>;
  headers?: Record<string, string>;
}

export class UnifiedClient {
  private config: ClientConfig;
  private adapters: Map<Platform, PlatformAdapter> = new Map();

  constructor(config: ClientConfig) {
    this.config = config;
    this.initAdapters();
  }

  private initAdapters(): void {
    for (const [platform, platformConfig] of Object.entries(this.config.platforms)) {
      this.adapters.set(platform as Platform, new PlatformAdapter(platform as Platform, platformConfig));
    }
  }

  getAdapter(platform: Platform): PlatformAdapter | undefined {
    return this.adapters.get(platform);
  }

  get primaryAdapter(): PlatformAdapter | undefined {
    const primary = this.config.primaryPlatform || Array.from(this.adapters.keys())[0];
    return this.adapters.get(primary);
  }

'''
    
    # Generate command methods
    for cmd_name, cmd_config in commands.items():
        method_name = cmd_name.replace(":", "_").replace("-", "_")
        args = cmd_config.get("args", [])
        orchestration = cmd_config.get("orchestration", {})
        
        # Build parameter list
        params = []
        for arg in args:
            arg_name = arg.get("name", "")
            arg_type = {"string": "string", "integer": "number", "boolean": "boolean"}.get(arg.get("type", "string"), "string")
            required = arg.get("required", False)
            optional = "" if required else "?"
            params.append(f"{arg_name}{optional}: {arg_type}")
        
        param_str = ", ".join(params) if params else ""
        
        client_content += f'''
  /**
   * {cmd_config.get("description", cmd_name)}
   */
  async {method_name}({param_str}): Promise<Record<string, unknown>> {{
    const orchestrationType = '{orchestration.get("type", "single")}';
    
'''
        
        if orchestration.get("type") == "parallel":
            client_content += f'''    const platforms: Platform[] = {json.dumps(orchestration.get("platforms", []))};
    const targetPlatforms = platforms[0] === 'all' 
      ? Array.from(this.adapters.keys()) 
      : platforms;
    
    const results: Record<string, unknown> = {{}};
    await Promise.all(
      targetPlatforms.map(async (platform) => {{
        const adapter = this.adapters.get(platform);
        if (adapter) {{
          try {{
            results[platform] = await adapter.execute('{cmd_name}', {{ {", ".join(f"{a['name']}" for a in args)} }});
          }} catch (error) {{
            results[platform] = {{ error: String(error) }};
          }}
        }}
      }})
    );
    return results;
'''
        elif orchestration.get("type") == "sequential":
            client_content += f'''    const steps = {json.dumps(orchestration.get("steps", []))};
    const context: Record<string, unknown> = {{ {", ".join(f"{a['name']}" for a in args)} }};
    const results: unknown[] = [];
    
    for (const step of steps) {{
      const platform = step.platform?.replace(/{{(\\w+)}}/g, (_: string, key: string) => String(context[key] || ''));
      const adapter = this.adapters.get(platform as Platform);
      if (adapter) {{
        const result = await adapter.executeStep(step, context);
        results.push({{ step: step.action, platform, result }});
        Object.assign(context, result);
      }}
    }}
    return {{ steps: results, context }};
'''
        else:
            client_content += f'''    const platform = '{orchestration.get("platform", "primary")}';
    const adapter = platform === 'primary' ? this.primaryAdapter : this.adapters.get(platform as Platform);
    if (!adapter) {{
      throw new Error(`Platform ${{platform}} not configured`);
    }}
    return adapter.execute('{cmd_name}', {{ {", ".join(f"{a['name']}" for a in args)} }});
'''
        
        client_content += "  }\n"
    
    client_content += '''
}

export class PlatformAdapter {
  private platform: Platform;
  private config: PlatformConfig;
  private rateLimiter: RateLimiter;

  constructor(platform: Platform, config: PlatformConfig) {
    this.platform = platform;
    this.config = config;
    this.rateLimiter = new RateLimiter(config.rateLimit);
  }

  async request<T>(endpoint: string, options: RequestOptions = {}): Promise<T> {
    await this.rateLimiter.acquire();
    
    const url = `${this.config.baseUrl}${endpoint}`;
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.getAuthHeaders(),
      ...options.headers,
    };

    const response = await fetch(url, {
      method: options.method || 'GET',
      headers,
      body: options.body ? JSON.stringify(options.body) : undefined,
    });

    if (!response.ok) {
      const error: ApiError = {
        code: `${response.status}`,
        message: response.statusText,
        platform: this.platform,
      };
      throw error;
    }

    return response.json();
  }

  private getAuthHeaders(): Record<string, string> {
    const { auth } = this.config;
    switch (auth.type) {
      case 'oauth2':
      case 'token':
        return { Authorization: `Bearer ${auth.token}` };
      case 'api_key':
        return { Authorization: `Bearer ${auth.apiKey}` };
      default:
        return {};
    }
  }

  async execute(command: string, args: Record<string, unknown>): Promise<Record<string, unknown>> {
    // Override in platform-specific adapters
    console.log(`Executing ${command} on ${this.platform} with args:`, args);
    return { platform: this.platform, command, args };
  }

  async executeStep(step: Record<string, unknown>, context: Record<string, unknown>): Promise<Record<string, unknown>> {
    // Override in platform-specific adapters
    console.log(`Executing step on ${this.platform}:`, step, context);
    return {};
  }
}

class RateLimiter {
  private tokens: number;
  private maxTokens: number;
  private refillRate: number;
  private lastRefill: number;

  constructor(config?: RateLimitConfig) {
    this.maxTokens = config?.requests || 100;
    this.tokens = this.maxTokens;
    this.refillRate = this.parseRefillRate(config?.period || '1s');
    this.lastRefill = Date.now();
  }

  private parseRefillRate(period: string): number {
    const match = period.match(/(\\d+)(s|m|h)/);
    if (!match) return 1000;
    const [, value, unit] = match;
    const multiplier = { s: 1000, m: 60000, h: 3600000 }[unit] || 1000;
    return parseInt(value) * multiplier;
  }

  async acquire(): Promise<void> {
    this.refill();
    if (this.tokens <= 0) {
      const waitTime = this.refillRate / this.maxTokens;
      await new Promise(resolve => setTimeout(resolve, waitTime));
      this.refill();
    }
    this.tokens--;
  }

  private refill(): void {
    const now = Date.now();
    const elapsed = now - this.lastRefill;
    const tokensToAdd = Math.floor(elapsed / this.refillRate) * this.maxTokens;
    this.tokens = Math.min(this.maxTokens, this.tokens + tokensToAdd);
    this.lastRefill = now;
  }
}

export default UnifiedClient;
'''
    
    (output_dir / "client.ts").write_text(client_content)
    print(f"   ✓ Generated client.ts")


def generate_typescript_cli(config: Dict[str, Any], output_dir: Path) -> None:
    """Generate TypeScript CLI entry point."""
    commands = config.get("commands", {})
    
    cli_content = '''#!/usr/bin/env node
/**
 * Unified CLI for multiplatform API integration.
 * DO NOT EDIT - Generated by multiplatform-api-weaver
 */

import { UnifiedClient, ClientConfig } from './client';
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'yaml';

interface CliArgs {
  command: string;
  config: string;
  format: 'json' | 'table' | 'raw';
  [key: string]: string | number | boolean;
}

function loadConfig(configDir: string): ClientConfig {
  const config: Record<string, unknown> = {};
  const files = fs.readdirSync(configDir).filter(f => f.endsWith('.yaml'));
  
  for (const file of files) {
    const content = fs.readFileSync(path.join(configDir, file), 'utf-8');
    Object.assign(config, yaml.parse(content));
  }
  
  return config as unknown as ClientConfig;
}

function formatOutput(data: unknown, format: string): string {
  if (format === 'json') {
    return JSON.stringify(data, null, 2);
  } else if (format === 'table' && Array.isArray(data)) {
    if (data.length === 0) return 'No results';
    const headers = Object.keys(data[0] as Record<string, unknown>);
    const rows = data.map(item => headers.map(h => String((item as Record<string, unknown>)[h] || '')));
    const widths = headers.map((h, i) => Math.max(h.length, ...rows.map(r => r[i].length)));
    const headerLine = headers.map((h, i) => h.padEnd(widths[i])).join(' | ');
    const separator = widths.map(w => '-'.repeat(w)).join('-+-');
    const dataLines = rows.map(r => r.map((c, i) => c.padEnd(widths[i])).join(' | ')).join('\\n');
    return `${headerLine}\\n${separator}\\n${dataLines}`;
  }
  return String(data);
}

function parseArgs(): CliArgs {
  const args = process.argv.slice(2);
  const result: CliArgs = {
    command: '',
    config: './config',
    format: 'json',
  };
  
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg.startsWith('--')) {
      const key = arg.slice(2);
      const value = args[++i];
      result[key] = value;
    } else if (!result.command) {
      result.command = arg;
    }
  }
  
  return result;
}

async function main(): Promise<void> {
  const args = parseArgs();
  
  if (!args.command) {
    console.log('Usage: weaver <command> [options]');
    console.log('\\nCommands:');
'''
    
    for cmd_name, cmd_config in commands.items():
        cli_content += f"    console.log('  {cmd_name.ljust(20)} {cmd_config.get(\"description\", \"\")}');\n"
    
    cli_content += '''    process.exit(0);
  }
  
  const config = loadConfig(args.config);
  const client = new UnifiedClient(config);
  
  const methodName = args.command.replace(':', '_').replace('-', '_');
  const method = (client as unknown as Record<string, Function>)[methodName];
  
  if (!method) {
    console.error(`Unknown command: ${args.command}`);
    process.exit(1);
  }
  
  try {
    const result = await method.call(client, args);
    console.log(formatOutput(result, args.format));
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

main();
'''
    
    (output_dir / "cli.ts").write_text(cli_content)
    print(f"   ✓ Generated cli.ts")


def generate_python_client(config: Dict[str, Any], output_dir: Path) -> None:
    """Generate Python unified client (simplified version)."""
    # Similar to TypeScript but in Python
    print("   ✓ Python client generation (use init_integration.py for full Python project)")


def main():
    parser = argparse.ArgumentParser(description="Generate unified client from configuration")
    parser.add_argument("--config", required=True, help="Configuration directory")
    parser.add_argument("--output", required=True, help="Output directory")
    parser.add_argument("--language", choices=["typescript", "python"], default="typescript")
    
    args = parser.parse_args()
    
    config_dir = Path(args.config)
    output_dir = Path(args.output)
    
    if not config_dir.exists():
        print(f"❌ Config directory not found: {config_dir}")
        sys.exit(1)
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"🔧 Generating {args.language} client from {config_dir}")
    
    config = load_config(config_dir)
    
    if args.language == "typescript":
        generate_typescript_types(config, output_dir)
        generate_typescript_client(config, output_dir)
        generate_typescript_cli(config, output_dir)
    else:
        generate_python_client(config, output_dir)
    
    print(f"\n✅ Client generated successfully in {output_dir}")


if __name__ == "__main__":
    main()
