#!/usr/bin/env python3
"""
share_template.py — Package a decomposed skill template for community sharing.

Creates a shareable template bundle containing the template manifest, domain bindings,
structure map, and a README for community members to instantiate in their own domains.

Usage:
    python share_template.py <decomposed_dir> [--output <bundle_path>] [--format tar|dir]

Arguments:
    decomposed_dir   Path to decomposed skill output (from decompose_skill.py)
    --output         Output path for the bundle (default: ./<skill_name>_template.tar.gz)
    --format         Bundle format: 'tar' (compressed archive) or 'dir' (directory)
    --readme         Include a generated README.md for community users

Example:
    python share_template.py ./fnb_template --format dir --output ./shared_templates/fnb
"""

import argparse
import os
import sys
import tarfile
import shutil
from pathlib import Path
from datetime import datetime

try:
    import yaml
    def load_yaml(path):
        with open(path) as f:
            return yaml.safe_load(f)
except ImportError:
    import json
    def load_yaml(path):
        with open(path) as f:
            try:
                return yaml.safe_load(f)
            except:
                return json.load(f)


def generate_readme(manifest: dict, bindings: dict) -> str:
    """Generate a community-facing README for the template."""
    source = manifest.get("meta", {}).get("source_skill", "unknown")
    slots = manifest.get("parameterized_slots", {})
    structure = manifest.get("invariant_structure", {})

    lines = [
        f"# Skill Template: {source}",
        "",
        f"A reusable skill template derived from **{source}**.",
        "",
        "## What This Template Provides",
        "",
        f"- **{len(structure.get('sections', []))}** structural sections",
        f"- **{len(structure.get('workflow_steps', []))}** workflow steps",
        f"- **{structure.get('script_count', 0)}** scripts",
        f"- **{structure.get('reference_count', 0)}** reference documents",
        f"- **{structure.get('template_count', 0)}** output templates",
        "",
        "## Parameterized Slots",
        "",
        "Configure these slots to transform the template into your target domain:",
        "",
        "| Slot | Current Value | Description |",
        "|------|---------------|-------------|",
    ]

    for slot_name, slot_info in slots.items():
        current = slot_info.get("current", "")
        desc = slot_info.get("description", "")
        display = str(current)[:40] + "..." if len(str(current)) > 40 else str(current)
        lines.append(f"| `{slot_name}` | {display} | {desc} |")

    lines.extend([
        "",
        "## How to Use",
        "",
        "### 1. Create a Transform Specification",
        "",
        "Create a YAML file with your domain-specific values:",
        "",
        "```yaml",
        "slot_mappings:",
        f"  name: your-new-skill-name",
        f"  description: Your skill description",
        f"  primary_domain: your_domain",
        "",
        "term_mappings:",
        "  old_term_1: new_term_1",
        "  old_term_2: new_term_2",
        "```",
        "",
        "### 2. Run the Transformation",
        "",
        "```bash",
        f"python /home/ubuntu/skills/function-creator/scripts/transform_skill.py \\",
        f"    template_manifest.yaml \\",
        f"    your_transform_spec.yaml",
        "```",
        "",
        "### 3. Review and Customize",
        "",
        "The transformation preserves structure but you should:",
        "- Review SKILL.md for domain accuracy",
        "- Update scripts with domain-specific logic",
        "- Add domain-specific references",
        "- Test with real tasks",
        "",
        "## Composition",
        "",
        "This template can be chained with other templates using `chain_transforms.py`.",
        "See the function-creator skill documentation for details.",
        "",
        f"---",
        f"*Generated by function-creator on {datetime.now().strftime('%Y-%m-%d')}*",
    ])

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Package a skill template for sharing")
    parser.add_argument("decomposed_dir", help="Path to decomposed skill output")
    parser.add_argument("--output", "-o", help="Output path for the bundle")
    parser.add_argument("--format", choices=["tar", "dir"], default="dir", help="Bundle format")
    parser.add_argument("--readme", action="store_true", default=True, help="Include README.md")
    args = parser.parse_args()

    src = Path(args.decomposed_dir).resolve()
    if not src.exists():
        print(f"ERROR: {src} does not exist", file=sys.stderr)
        sys.exit(1)

    # Load manifest for metadata
    manifest_path = src / "template_manifest.yaml"
    bindings_path = src / "domain_bindings.yaml"

    manifest = load_yaml(manifest_path) if manifest_path.exists() else {}
    bindings = load_yaml(bindings_path) if bindings_path.exists() else {}

    source_name = manifest.get("meta", {}).get("source_skill", src.name)

    # Determine output
    if args.output:
        output = Path(args.output).resolve()
    else:
        output = Path.cwd() / f"{source_name}_template"
        if args.format == "tar":
            output = output.with_suffix(".tar.gz")

    print(f"📦 Packaging template: {source_name}")
    print(f"   Source: {src}")
    print(f"   Output: {output}")

    if args.format == "dir":
        # Copy to output directory
        if output.exists():
            shutil.rmtree(output)
        shutil.copytree(src, output)

        # Generate README
        if args.readme:
            readme = generate_readme(manifest, bindings)
            (output / "README.md").write_text(readme, encoding="utf-8")
            print(f"✅ Generated README.md")

        print(f"✅ Template packaged: {output}")

    elif args.format == "tar":
        # Create temp dir with README, then tar
        import tempfile
        with tempfile.TemporaryDirectory() as tmpdir:
            bundle_dir = Path(tmpdir) / f"{source_name}_template"
            shutil.copytree(src, bundle_dir)

            if args.readme:
                readme = generate_readme(manifest, bindings)
                (bundle_dir / "README.md").write_text(readme, encoding="utf-8")

            with tarfile.open(output, "w:gz") as tar:
                tar.add(bundle_dir, arcname=bundle_dir.name)

        print(f"✅ Template archived: {output}")

    print(f"\nShare this template with community members.")
    print(f"They can transform it into their domain using:")
    print(f"  python transform_skill.py template_manifest.yaml their_transform.yaml")


if __name__ == "__main__":
    main()
